### ISSUE TITLE
Support encrypt of PlaintextDocument using existing EDEK

### ISSUE THREAD

**Issue by coltfred** [IronCoreLabs/tenant-security-client-php#22]
We are currently missing the encrypt function that takes an existing edek to use.

This function is [here](https://github.com/IronCoreLabs/tenant-security-client-java/blob/main/src/main/java/com/ironcorelabs/tenantsecurity/kms/v1/TenantSecurityClient.java#L376) in java. We should add it in this sdk as well to allow for the usecase where someone wants to share an edek across many calls to encrypt.

In node we call this `encryptWithExistingKey`.

**Comment by skeet70** [comment]
A customer didn't realize this method was an option and implemented their own version of it manually calling the TSP. We should up the priority of implementing this so they can use it.
