### ISSUE TITLE
Fix data format on Plaintext Document

### ISSUE THREAD

**Issue by skeet70** [IronCoreLabs/tenant-security-client-php#30]
All our other TSCs return plaintext documents filled with direct byte representations and an EDEK that is base64. This TSC returns plaintext documents filled with base64 and EDEKs that are direct byte representations. Introduce a breaking change to fix this library, probably along with #29

**Comment by giarc3** [comment]
This TSC returns `Bytes` for both the documents and the EDEK. These `Bytes` can be stored as either base64 or directly as bytes with the `getBase64String` and `getByteString` methods. This gives more flexibility over the other TSCs.
